return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use 'nvim-lualine/lualine.nvim'
  use 'Mofiqul/dracula.nvim'
  use {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'}
  use 'preservim/nerdtree'
  use 'bfrg/vim-c-cpp-modern'
  use 'ryanoasis/vim-devicons'
  use 'tc50cal/vim-terminal'
  use 'preservim/tagbar'
  --use 'terryma/vim-multiple-cursors'
  --use 'sheerun/vim-polyglot'
  use 'folke/tokyonight.nvim'
  use 'neovim/nvim-lspconfig'
  use 'hrsh7th/nvim-cmp'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'nvim-telescope/telescope.nvim'
  use 'lewis6991/gitsigns.nvim'
  use 'numToStr/Comment.nvim'
  use 'mfussenegger/nvim-dap'
  use 'rcarriga/nvim-dap-ui'
  use 'L3MON4D3/LuaSnip'
  use 'windwp/nvim-autopairs'
  use 'norcalli/nvim-colorizer.lua'
  use 'ahmedkhalf/project.nvim'
end)
